# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
# You must relaunch Hyprland after changing any envs (use Super+Esc, then Relaunch)

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
# env = GDK_SCALE,2
# monitor=,preferred,auto,auto

# Good compromise for 27" or 32" 4K monitors (but fractional!)
# env = GDK_SCALE,1.75
# monitor=,preferred,auto,1.666667

# Straight 1x setup for low-resolution displays like 1080p or 1440p
# env = GDK_SCALE,1
# monitor=,preferred,auto,1

# Example for Framework 13 w/ 6K XDR Apple display
# monitor = DP-5, 6016x3384@60, auto, 2
# monitor = eDP-1, 2880x1920@120, auto, 2

# Laptop monitor - disabled by default, enabled by lid switch script when no external monitors
monitor=desc:Chimei Innolux Corporation 0x1777,disable
monitor=desc:Dell Inc. Dell U4919DW BJ6NXH3,5120x1440@59.98,0x220,1.0
monitor=desc:Dell Inc. DELL P2725H 8NVYWZ3,1920x1080@60.0,5120x0,1.0,transform,1
monitor=desc:Dell Inc. DELL P2722H 7JBHZG3,1920x1080@60.0,6200x500,1.0
